### PR TITLE
changed file.md

### LINKED ISSUE #26: Documentation for file command
- add a short description for `file` command
- add some examples

### PR DESCRIPTION
**Pull request by insualk**
# Advanced HW 5 submission

Closes #26 

Name: Xiangliang Ni
Uniqname: nixl

## Description of Changes

Added a description and some examples for command `file`

### CODE REVIEW

**Comment by samkhn** [comment]
Hey. This is a great start. But there are a few things I was hoping you could add... (questions a reader might have)

1. Unix doesn't just have text files. What other files can I pass to `file`? Can I pass an executable to it? What would it print?
2. What character sets are supported? I know everything essentially supports but what about Unicode and UTF8? Can I pass those files to `file`?

**Comment by samkhn** [comment]
Do you plan on addressing comments above?

**Comment by insualk** [comment]
Yes. Thank you for the comment!

**Comment by samkhn** [comment]
We're sorry but we expected a response within a week of the initial comment. We will not be awarding credit for this.

**Pull request closed without merging**
