### PR TITLE
Documentation for hostname

### LINKED ISSUE #117: Documentation for hostname command

### PR DESCRIPTION
**Pull request by danherre**
# Advanced HW 5 submission

Closes #117

Name: Daniel Herrerias
Uniqname: danherre

### CODE REVIEW

**Comment by samkhn** [comment]
Just from reading this, I still have no idea what `hostname` is or does. Could you add a sentence or a paragraph describing what the command does and show example output someone might see if they call hostname with flags. Also do you need `sudo` privilege to run? What is newname and why do I need it?

(Grading note: you will have a week from today to add changes. Once you do, we'll come back and either LGTM it or ask for more changes).

**Comment by samkhn** [comment]
Hey. Could you add a few more flags that could be useful? Also unbold the description of what the flags are, it makes it difficult to distinguish the title and the text.

**Comment by danherre** [comment]
Hi Samiur,

On February 26th you emailed me saying that my most recent submission looked good, did something change?

Thank you,

Danny

**Comment by stevietriesenberg** [comment]
Credit awarded, +2 ec

**Pull request closed without merging**
