### PR TITLE
fixed chsh documentation and formatting

### LINKED ISSUE #157: Fixed formatting for chsh and added more documentation

### PR DESCRIPTION
**Pull request by prathits012**
# Advanced HW 5 submission

Closes #157 

Name: Prathit Shukla
Uniqname: prathit

## Description of Changes
Fixed formatting of the chsh on the main website

The formatting before was incorrect due to the previous editor making a mistake in Markdown forgetting to put the advanced options on the link of the page. Instead it was put on the preview of this tag which is now fixed.
Also added additional documentation for different options

### CODE REVIEW

**Comment by samkhn** [comment]
Hmm this looks like a modification to someone else's work. The assignment wanted students to take an unclaimed command and write a reference page for it.

**Comment by prathits012** [comment]
I thought Tarun mentioned during the office hrs ++ session that we are
allowed to add to someone else's work as well if we saw something to add. I
still feel I fixed a flaw on the design of the website.

Thanks,

-Prathit

**Comment by samkhn** [comment]
Ya modifications are okay but they need to be more than just a few lines. I suggest maybe adding 2-3 more uses of chsh with its flags. Or maybe how chsh works.

Also upon reading it... what does "this file" refer to in the line you did add?

You have until 12/6 11:59pm to make changes.

**Comment by prathits012** [comment]
Added a new commit addressing those issues. Not sure if I have done it correctly to attach it to this message.

**Comment by samkhn** [comment]
This is better (key metric was how many novel pieces of info you added). Awarded 2 extra credit for early submission.

**Pull request merged**
