### PR TITLE
Logname Files-Useful Command line-Telling your current log in name

### PR DESCRIPTION
**Pull request by bruceyan1996**
# Advanced HW 5 submission

Closes #[183]

Name: [Kun Yan]
Uniqname: [kuny]

### CODE REVIEW

**Comment by samkhn** [comment]
Hey. Your commit b97ce1d is not really working.

1. Not everything should be under header level 2, that makes headers unecessary.
2. You aren't really following markdown syntax. For instance code snippets go under a ```<snippet>``` like format.
3. Just pushing a bit on your example: under a public computer the logname would either be something public or if its a public machine with private accounts it'd likely have my name right? 3b. logname does have use though in adding a user to groups. Maybe explore that as well?

**Comment by bruceyan1996** [comment]
Dear Samiur: 

>    Thanks for checking over my work and leaving me with very specific comments, and I appreciate your time! Since certain header levels and markdown syntax are neither a requirement on the homework nor being mentioned during OH++, I thought it wouldn't stop me from getting the credits for this hw. I do agree that I should be more careful with it though for future references. 

>   In addition to that, a public machine could have numerous accounts/log names. In some languages, it is easy to make a mistake by choosing a similar but wrong account if people are not careful enough with log names.  I think what you are suggesting might cover the majority of cases, but it is undeniable that checking log names could be beneficial for some populations, some circumstances in the world. 

Thank you again!

**Comment by samkhn** [comment]
> Since certain header levels and markdown syntax are neither a requirement on the homework nor being mentioned during OH++, I thought it wouldn't stop me from getting the credits for this hw.

Your file extension is .md which is markdown, hence we want valid markdown syntax. Because markdown isn't compiled (similar to HTML), you test it by running the server and just looking at the rendered markdown page (the server does the work of converting to HTML). It's generally assumed that any code you submit anywhere where other people will use your code (e.g. a workplace, class with autograder, public wiki, etc...) should work before submission. This doesn't apply of course for code just for yourself (toy code, personal projects, etc...).

> it is easy to make a mistake by choosing a similar but wrong account if people are not careful enough with log names. 

Okay that sounds good. Can you add to the reference you wrote to show an example of this? Perhaps a bash script with a hard coded and wrong username and then an example with `logname` that fixes this?

Also you have a December 6th to fix this. If you intend on fixing this, just checkout to the fork and branch this PR references and just push changes to it.

**Comment by bruceyan1996** [comment]
Hi Samiur:

   I have made changes to syntax errors and the format, and I also added a few features of logname.  Please let me know if this will work at this time. I sincerely appreciate your time! 

Best Regards

**Comment by samkhn** [comment]
LGTM. Awarded 2 extra credit for early submission.

**Pull request merged**
